export const API_ERROR_CODES = {
    INVALID_JSON: 'INVALID_JSON',
    VERIFY_FAILED: 'VERIFY_FAILED',
    VERIFY_LOCKED: 'VERIFY_LOCKED',
    SESSION_EXPIRED: 'SESSION_EXPIRED',
    CASE_SUBMITTED: 'CASE_SUBMITTED',
    CASE_SUBMITTED_READONLY: 'CASE_SUBMITTED_READONLY',
    CASE_NOT_FOUND: 'CASE_NOT_FOUND',
    CHAT_TOO_MANY_MESSAGES: 'CHAT_TOO_MANY_MESSAGES',
    CHAT_MESSAGE_TOO_LARGE: 'CHAT_MESSAGE_TOO_LARGE',
    UPLOAD_UNSUPPORTED_TYPE: 'UPLOAD_UNSUPPORTED_TYPE',
    UPLOAD_NOT_CONFIGURED: 'UPLOAD_NOT_CONFIGURED',
    FILE_TOO_LARGE: 'FILE_TOO_LARGE',
    UPLOAD_FAILED: 'UPLOAD_FAILED',
    UPLOAD_LIMIT_EXCEEDED: 'UPLOAD_LIMIT_EXCEEDED',
    CHAT_DISABLED: 'CHAT_DISABLED',
    OTP_INVALID: 'OTP_INVALID',
    OTP_EXPIRED: 'OTP_EXPIRED',
    OTP_RATE_LIMITED: 'OTP_RATE_LIMITED',
    PARTNER_NOT_ALLOWED: 'PARTNER_NOT_ALLOWED',
    INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
    PARTNER_SESSION_EXPIRED: 'PARTNER_SESSION_EXPIRED',
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];

export function apiErrorResponse(
    code: ApiErrorCode,
    status: number,
    logMessage?: string,
): Response {
    return Response.json(
        {
            code,
            error: logMessage ?? code,
        },
        { status },
    );
}
